# Generated by Django 6.0.1 on 2026-01-27 16:06

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_test_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='testuser').exists():
        User.objects.create(
            username='testuser',
            password=make_password('Xk9#mP2$vL5nQ8wR')
        )


def remove_test_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='testuser').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_user, remove_test_user),
    ]
