# Generated by Django 6.0.1 on 2026-01-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_seed_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='todo',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
